name: "ARTIFACTS"

on:
  workflow_dispatch:

jobs:
  job_1:
    name: ARTIFACTS upload
    runs-on: ubuntu-latest
    steps:
      - name: upload
        run: echo "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat velit aperiam sit illo maiores at quas."
      - uses: actions/upload-artifacts@v2
        with:
          name: file
          path: file.txt
          retention-days: 10

  job_2:
    name: ARTIFACTS upload
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifacts@v2
        with:
          name: file
      - run: cat file.txt
