name: My Workflow

on:
  push:
    branches:
      - main # Adjust this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, world!"

  build-app:
    needs: build
    runs-on: windows-latest

  package:
    needs: [build-app, build]
    runs-on: self-hosted
