name: My Workflow

on:
  push:
    branches:
      - main # Adjust this to match your branch name

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, world!"

      - name: Print a message
        run: |
          echo "Hello, world!"
          echo "Hello, world!"

  build-app:
    # needs: build
    runs-on: windows-latest

    steps:
      - run: echo "hello windows"

  package:
    # needs: [build-app, build]
    runs-on: macos-latest
    steps:
      - run: echo "hello mack"
