name: "set ENV demo"

on:
  workflow_dispatch:

jobs:
  custome-set-ENV:
    name: "set env"
    runs-on: ubuntu-latest

    steps:
      - name: set-values-of-env
        id: step_one
        run: |
          echo "action_state = yellow" >> $GITHUB_ENV

      - name: use the value
        id: step_two
        run: |
          echo "$action_state" #output
